# Generated by Django 5.0.4 on 2024-05-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcategory',
            name='files',
        ),
        migrations.RemoveField(
            model_name='category',
            name='files',
        ),
        migrations.AddField(
            model_name='category',
            name='files',
            field=models.ManyToManyField(blank=True, to='base.file'),
        ),
    ]
