# Generated by Django 4.1.3 on 2023-10-05 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_tb',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
