# Generated by Django 5.0.4 on 2024-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_historicalcategory_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfile',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
    ]
