# Generated by Django 5.0.4 on 2024-05-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfolder',
            name='files',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='files',
        ),
        migrations.AddField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, to='base.file'),
        ),
    ]
