# Generated by Django 5.0.4 on 2024-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_category_created_at_alter_file_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
