# Generated by Django 5.0.4 on 2024-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_folder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='historicalfolder',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
